<?php

namespace App\Http\Controllers\Admin;

use App\Models\DealModel;
use App\Models\LeadModel;
// use Illuminate\Http\Request;
// use App\Http\Controllers\Controller;

trait AutoGeneratedController
{
	public function autoId($type){

		if ($type=='lead'){
			$leadCount = LeadModel::count();
			if ($leadCount==0) {
				$id = 1;
			} else {
				$lastId = LeadModel::orderBy('id', 'desc')->first();
				$id = $lastId->id + 1;
			}
		}else{
			$dealCount = DealModel::count();
			if ($dealCount==0) {
				$id = 1;
			} else {
				$lastId = DealModel::orderBy('id', 'desc')->first();
				$id = $lastId->id + 1;
			}
		}
		if (strlen($id) == 1){$id = '000' . $id;}
		else if (strlen($id) == 2){$id = '00' . $id;}
		else if (strlen($id) == 3){$id = '0' . $id;}
		else{$id = $id;}

		return $id;
	}
}